demoTranslatorChat/Models/TranslateContent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace demoTranslatorChat.Models
{
    public class TranslateContent
    {
        [Display(Name="Text to Translate")]
        [DataType(DataType.MultilineText)]
        public string TextToTranslate { get; set; }

        [Display(Name="Translation")]
        public string TranslatedText { get; set; }
    }
}

demoTranslatorChat/Models/TranslateContentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace demoTranslatorChat.Models
{
    public class TranslateContentViewModel
    {

        public TranslateContent TransalateContentModel { get; set; }
        public IEnumerable<SelectListItem> SourceLanguage { get { return new SelectList(_languages, "Id", "Name"); } }
        public IEnumerable<SelectListItem> DestinationLanguage { get { return new SelectList(_languages, "Id", "Name"); } }

        public string SelectedSourceLanguage { get; set; }
        public string SelectedDestLanguage { get; set; }
        

        public TranslateContentViewModel() {
            _languages = new List<PerLanguage> { new PerLanguage { Id = "en", Name = "English" }, new PerLanguage { Id = "es", Name = "Spanish" },
                                                new PerLanguage{ Id = "it", Name = "Italian"}, new PerLanguage{ Id = "fr", Name = "French"}};

            this.SelectedDestLanguage = "es";

            

        }



        public System.Collections.IEnumerable _languages { get; set; }
    }


    public class PerLanguage {
        public string Id { get; set; }
        public string Name { get; set; }
    }
}

demoTranslatorChat/Controllers/TranslateContentController.cs
using demoTranslatorChat.Models;
using demoTranslatorChat.Translator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace demoTranslatorChat.Controllers
{
    public class TranslateContentController : Controller
    {
        
        // GET: TranlateContent
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ViewResult Translate()
        {
            TranslateContentViewModel model = new TranslateContentViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ViewResult Translate(TranslateContentViewModel model) {

            TranslationHistoryViewModel tmpList = null;

            if (Session["TranslatedHistory"] != null)
            {
                tmpList = (TranslationHistoryViewModel)Session["TranslatedHistory"];
            }
            else
	        {
                    tmpList = new TranslationHistoryViewModel();
                    Session.Add("TranslatedHistory", tmpList);
	        }



            AdmAccessToken headerValue = null;

            if (Session["AdmToken"] == null || (Session["AdmToken"] != null && ((AdmAccessToken)Session["AdmToken"]).IsExpired()))
            {
                Session.Remove("AdmToken");
                headerValue = GetBearerTokenMSTranslator();
                Session.Add("AdmToken", headerValue);
            }
            else
            {
                headerValue = (AdmAccessToken)Session["AdmToken"];
            }
            

            //Required connection elements acquired.

            string txtToTranslate = model.TransalateContentModel.TextToTranslate;
            string uri = "http://api.microsofttranslator.com/v2/Http.svc/Translate?text=" +
                 System.Web.HttpUtility.UrlEncode(txtToTranslate) + "&from="+model.SelectedSourceLanguage+"&to="+model.SelectedDestLanguage;
            System.Net.WebRequest translationWebRequest = System.Net.WebRequest.Create(uri);
            translationWebRequest.Headers.Add("Authorization", headerValue.ToString());

            System.Net.WebResponse response = null;
            response = translationWebRequest.GetResponse();
            System.IO.Stream stream = response.GetResponseStream();
            System.Text.Encoding encode = System.Text.Encoding.GetEncoding("utf-8");

            System.IO.StreamReader translatedStream = new System.IO.StreamReader(stream, encode);
            System.Xml.XmlDocument xTranslation = new System.Xml.XmlDocument();
            xTranslation.LoadXml(translatedStream.ReadToEnd());

            model.TransalateContentModel.TranslatedText = xTranslation.InnerText;

            //model.TransalateContentModel.TranslatedText = model.TransalateContentModel.TextToTranslate + " Translated";

            tmpList.History.Add(model.TransalateContentModel);
            Session["TranslatedHistory"] = tmpList;
            return View(model);
        }

       


        public PartialViewResult HistoryTranslate() {
            TranslationHistoryViewModel tmpList = null;

            if (Session["TranslatedHistory"] != null)
            {
                tmpList = (TranslationHistoryViewModel)Session["TranslatedHistory"];
            }
            else
            {
                tmpList = new TranslationHistoryViewModel();
                Session.Add("TranslatedHistory", tmpList);
            }

            return PartialView(tmpList);
        }

        [Authorize]
        public ActionResult Chat()
        {
            return View();
        }

        private static AdmAccessToken GetBearerTokenMSTranslator()
        {
            string clientID = "demotranslatorpmorales";
            string clientSecret = "2ddVMNYRJl0QmlQfYfSmqQqykFmnRcainqfKDk0LecE=";
            String strTranslatorAccessURI =
                  "https://datamarket.accesscontrol.windows.net/v2/OAuth2-13";
            String strRequestDetails =
                  string.Format("grant_type=client_credentials&client_id={0}&client_secret={1} &scope=http://api.microsofttranslator.com", HttpUtility.UrlEncode(clientID),
                      HttpUtility.UrlEncode(clientSecret));

            System.Net.WebRequest webRequest = System.Net.WebRequest.Create(strTranslatorAccessURI);
            webRequest.ContentType = "application/x-www-form-urlencoded";
            webRequest.Method = "POST";
            byte[] bytes = System.Text.Encoding.ASCII.GetBytes(strRequestDetails);
            webRequest.ContentLength = bytes.Length;
            using (System.IO.Stream outputStream = webRequest.GetRequestStream())
            {
                outputStream.Write(bytes, 0, bytes.Length);
            }

            System.Net.WebResponse webResponse = webRequest.GetResponse();
            System.Runtime.Serialization.Json.DataContractJsonSerializer serializer = new
                System.Runtime.Serialization.Json.DataContractJsonSerializer(typeof(AdmAccessToken));

            AdmAccessToken token =
                (AdmAccessToken)serializer.ReadObject(webResponse.GetResponseStream());
            token.Initalize();
            

            //string headerValue = "Bearer " + token.access_token;
            return token;
        }
    }
}

demoTranslatorChat/Views/TranslateContent/Chat.cshtml
@{
    ViewBag.Title = "Chat";
}

<h2>Chat</h2>
<div style="float:left; width:300px; " >
    <div id="connectedUser" style="opacity:0;" class="alert alert-success"></div>
    <ul id="users"></ul>
</div>

<div class="container" style="margin-left:350px;">
    @*<input type="text" id="message" class="form-control" style="width:450px; height:100px;" />*@
    <textarea id="message" class="form-control" style="width:450px; height:100px;" ></textarea>

    
    <select id="selectSourceLang" class="form-control">
        <option value="ar">Arabic</option>
        <option value="bg">Bulgarian</option>
        <option value="ca">Catalan</option>
        <option value="zh-CHS">Chinese Simplified</option>
        <option value="zh-CHT">Chinese Traditional</option>
        <option value="cs">Czech</option>
        <option value="da">Danish</option>
        <option value="nl">Dutch</option>
        <option value="en" selected="selected">English</option>
        <option value="et">Estonian</option>
        <option value="fi">Finnish</option>
        <option value="fr">French</option>
        <option value="de">German</option>
        <option value="el">Greek</option>
        <option value="ht">Haitian Creole</option>
        <option value="he">Hebrew</option>
        <option value="hi">Hindi</option>
        <option value="mww">Hmong Daw</option>
        <option value="hu">Hungarian</option>
        <option value="id">Indonesian</option>
        <option value="it">Italian</option>
        <option value="ja">Japanese</option>
        <option value="tlh">Klingon</option>
        <option value="tlh-Qaak">Klingon (pIqaD)</option>
        <option value="ko">Korean</option>
        <option value="lv">Latvian</option>
        <option value="lt">Lithuanian</option>
        <option value="ms">Malay</option>
        <option value="mt">Maltese</option>
        <option value="no">Norwegian</option>
        <option value="fa">Persian</option>
        <option value="pl">Polish</option>
        <option value="pt">Portuguese</option>
        <option value="ro">Romanian</option>
        <option value="ru">Russian</option>
        <option value="sk">Slovak</option>
        <option value="sl">Slovenian</option>
        <option value="es">Spanish</option>
        <option value="sv">Swedish</option>
        <option value="th">Thai</option>
        <option value="tr">Turkish</option>
        <option value="uk">Ukrainian</option>
        <option value="ur">Urdu</option>
        <option value="vi">Vietnamese</option>
        <option value="cy">Welsh</option>
    </select>

    <select id="selectDestLang" class="form-control">
        <option value="ar">Arabic</option>
        <option value="bg">Bulgarian</option>
        <option value="ca">Catalan</option>
        <option value="zh-CHS">Chinese Simplified</option>
        <option value="zh-CHT">Chinese Traditional</option>
        <option value="cs">Czech</option>
        <option value="da">Danish</option>
        <option value="nl">Dutch</option>
        <option value="en">English</option>
        <option value="et">Estonian</option>
        <option value="fi">Finnish</option>
        <option value="fr">French</option>
        <option value="de">German</option>
        <option value="el">Greek</option>
        <option value="ht">Haitian Creole</option>
        <option value="he">Hebrew</option>
        <option value="hi">Hindi</option>
        <option value="mww">Hmong Daw</option>
        <option value="hu">Hungarian</option>
        <option value="id">Indonesian</option>
        <option value="it">Italian</option>
        <option value="ja">Japanese</option>
        <option value="tlh">Klingon</option>
        <option value="tlh-Qaak">Klingon (pIqaD)</option>
        <option value="ko">Korean</option>
        <option value="lv">Latvian</option>
        <option value="lt">Lithuanian</option>
        <option value="ms">Malay</option>
        <option value="mt">Maltese</option>
        <option value="no">Norwegian</option>
        <option value="fa">Persian</option>
        <option value="pl">Polish</option>
        <option value="pt">Portuguese</option>
        <option value="ro">Romanian</option>
        <option value="ru">Russian</option>
        <option value="sk">Slovak</option>
        <option value="sl">Slovenian</option>
        <option value="es" selected="selected">Spanish</option>
        <option value="sv">Swedish</option>
        <option value="th">Thai</option>
        <option value="tr">Turkish</option>
        <option value="uk">Ukrainian</option>
        <option value="ur">Urdu</option>
        <option value="vi">Vietnamese</option>
        <option value="cy">Welsh</option>
    </select>

    <button type="button" class="btn btn-sm btn-default" id="sendmessage" >Send</button>
    <button type="button" class="btn btn-sm btn-primary" id="exitchat" >Exit</button>


    <input type="hidden" id="displayname" />
    <input type="hidden" id="preferedlang" />
    <ul id="discussion"></ul>
</div>



@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.1.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>

        function showDialog(aText) {

            $('#messageText').empty();
            $('#messageText').append(aText);
            $('#myModal').modal('show');
        }

        function playSound(soundname) {
            var thissound = document.getElementById(soundname);
            thissound.play();
        }

   
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name, message, originalText) {
                // Add the message to the page.
                $('#discussion').append('<li><div class="well well-sm"> <strong>' + htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) +
                    ' <button type="button" onclick="showDialog(\'' + htmlEncode(originalText) + '\')" class="btn btn-sm btn-default"  data-container="body"  data-toggle="popover" data-placement="right" data-content="' +
                    htmlEncode(originalText) +'">Source</button>' + '</div></li>');
                playSound('beep1');
                //$('#transcontent').popover();
                //$('#transcontent').click(function () {
                //    $('#transcontent').popover();

                //    //$('#transcontent').on('shown.bs.popover', function () {
                //    //    $('#transcontent').popover('hide')
                //    //});
                //});
            };

            chat.client.justJoined = function (justJoinedUser) {
                $("#connectedUser").append('<strong>' + justJoinedUser + ' is connected.</string>');
                $("#connectedUser").animate({ opacity: 100 }, 4000);
                $("#connectedUser").animate({ opacity: 0 }, 2000, function () { $("#connectedUser").empty(); });
            };

            chat.client.connectedUsers = function (users) {
                // Add the message to the page.

                $('#users').empty();
                users.forEach(function (entry) {
                    $('#users').append('<li><strong>' + entry + '</strong> </li>');
                });
                
            };

            chat.client.notificationMessage = function (aMessage) {
                showDialog(aMessage);
            };

            chat.client.userId = function (userId, preferedLanguage) {
                // Get the user name and store it to prepend to messages.
                $('#displayname').val(userId);
                $('#preferedlang').val(preferedLanguage);
            };
           

            
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    if ($('#message').val().trim() != '') {
                        chat.server.send($('#displayname').val(), $('#message').val(), $('#selectSourceLang').val(), $('#selectDestLang').val());
                    }
                    else {
                        showDialog("Enter a vaid text.");
                    }
                    
                    // Clear text box and reset focus for next comment.
                    
                });

                $('#exitchat').click(function () {
                    $.connection.hub.stop();
                    window.location.replace("/");
                });

                //$("#message").keyup(function (event) {
                //    if (event.keyCode == 13) {
                //        $("#sendmessage").click();
                //    }
                //});
                
                //chat.server.listConnectedUsers($('#displayname').val());
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

<div class="modal fade e bs-example-modal-sm" id="myModal">
    <div class="modal-dialog ">
        <div class="modal-content ">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Info</h4>
            </div>
            <div class="modal-body">
                <p id="messageText"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                @*<button type="button" class="btn btn-primary">Save changes</button>*@
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<audio id="beep" src="~/Media/BEEP2.WAV" autostart="false" enablejavascript="true">
    <audio id="beep1" src="~/Media/beep1.mp3" autostart="false" enablejavascript="true"></audio>

demoTranslatorChat/Views/TranslateContent/DisplayTranslatedChat.cshtml
@model demoTranslatorChat.Models.TranslateContent

<div>
    <i> @Html.DisplayFor(r => r.TextToTranslate) </i> -> <b> @Html.DisplayFor(r => r.TranslatedText); </b>
</div>

demoTranslatorChat/Views/TranslateContent/HistoryTranslate.cshtml
@model demoTranslatorChat.Models.TranslationHistoryViewModel

@if (Model != null)
{
 foreach (var translatedElement in Model.History)
 {
     Html.RenderPartial("DisplayTranslatedChat", translatedElement);
 
 }
}

demoTranslatorChat/Views/TranslateContent/Translate.cshtml
@model demoTranslatorChat.Models.TranslateContentViewModel

<table>
    <tr>
        @using (Ajax.BeginForm("Translate", "TranslateContent", new AjaxOptions() { UpdateTargetId = "translations" }))
        { 
            @Html.AntiForgeryToken()
        <td>
            @Html.LabelFor(r => r.TransalateContentModel.TextToTranslate)
        </td>
        <td>
            @Html.TextAreaFor(r => r.TransalateContentModel.TextToTranslate, 4, 15, new { @class = "form-control" }) 
            @Html.DropDownListFor(r => r.SelectedSourceLanguage, Model.SourceLanguage)
            @Html.DropDownListFor(r => r.SelectedDestLanguage, Model.DestinationLanguage)
            <input type="submit" value="Translate" class="btn btn-default" />
        </td>
        <td>
            @Html.LabelFor(r => r.TransalateContentModel.TranslatedText)
        </td>
        <td>
            @Html.DisplayFor(r => r.TransalateContentModel.TranslatedText)
        </td>
        }
    </tr>
    <tr>
       
        
    </tr>
</table>

<div id="translations">

    @{Html.RenderAction("HistoryTranslate");}

</div>